apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-api
  template:
    metadata:
      name: nest-api
      labels:
        app: nest-api
    spec:
      containers:
        - name: nest-api
          image: "fhmrk/imersaofsfc-desafio2-backend:latest"
          ports:
            - containerPort: 3000